import React, { useState } from 'react';
import { X, Sparkles, Loader2, Clapperboard } from 'lucide-react';
import { Episode, Guest, Production, Show, ShowFormat } from '../types';
import { api } from '../services/api';

interface NewEpisodeModalProps {
  isOpen: boolean;
  onClose: () => void;
  shows: Show[];
  productions?: Production[];
  guests: Guest[];
  onCreateEpisode: (episode: Partial<Episode>) => Promise<Episode>;
}

const FORMATS: ShowFormat[] = [
  'Entrevista',
  'Programa Solo',
  'Mesa Redonda',
  'Podcast/Videocast',
  'Debate',
  'Reportagem',
  'Especial',
  'Outro',
];

export const NewEpisodeModal: React.FC<NewEpisodeModalProps> = ({
  isOpen,
  onClose,
  shows,
  productions = [],
  guests,
  onCreateEpisode,
}) => {
  const defaultShow = shows[0];
  const defaultShowProductions = productions.filter((p) => p.showId === defaultShow?.id);

  const [showId, setShowId] = useState(defaultShow?.id || '');
  const [productionId, setProductionId] = useState(defaultShowProductions[0]?.id || '');
  const [title, setTitle] = useState('');
  const [idea, setIdea] = useState('');
  const [guestId, setGuestId] = useState<string>('');
  const [guestName, setGuestName] = useState('');
  const [host, setHost] = useState(defaultShow?.host || '');
  const [format, setFormat] = useState<ShowFormat>(defaultShow?.format || 'Entrevista');
  const [targetDurationMin, setTargetDurationMin] = useState(
    defaultShow?.defaultDurationMin || 45
  );
  const [objective, setObjective] = useState('');
  const [additionalInfo, setAdditionalInfo] = useState('');
  const [autoGenerateDiagnosis, setAutoGenerateDiagnosis] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);

  if (!isOpen) return null;

  const handleShowChange = (id: string) => {
    setShowId(id);
    const found = shows.find((s) => s.id === id);
    if (found) {
      setHost(found.host);
      setFormat(found.format);
      setTargetDurationMin(found.defaultDurationMin);
    }
    const prods = productions.filter((p) => p.showId === id);
    setProductionId(prods[0]?.id || '');
  };

  const handleGuestSelect = (id: string) => {
    setGuestId(id);
    if (id) {
      const g = guests.find((x) => x.id === id);
      if (g) setGuestName(g.name);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    setIsSubmitting(true);
    try {
      const selectedShow = shows.find((s) => s.id === showId) || shows[0];
      let diagnosis = {
        centralTheme: '',
        potentialStory: '',
        primaryConflict: '',
        primaryTransformation: '',
        whyWatch: '',
        whatToDiscover: '',
        researchPoints: [] as string[],
        highImpactMoments: [] as string[],
        approved: false,
      };

      if (autoGenerateDiagnosis) {
        diagnosis = await api.generateDiagnosis({
          showTitle: selectedShow?.title || 'Programa',
          showStyle: selectedShow?.editorialStyle || 'Entrevista profunda',
          episodeTitle: title,
          guestName: guestName || 'Convidado',
          idea,
          objective,
          additionalInfo,
        });
      }

      await onCreateEpisode({
        showId: selectedShow?.id || showId,
        productionId: productionId || undefined,
        title,
        idea,
        guestId: guestId || undefined,
        guestName,
        host,
        format,
        targetDurationMin,
        objective,
        additionalInfo,
        status: autoGenerateDiagnosis ? 'diagnosis' : 'draft',
        cameras: selectedShow?.cameras || [],
        diagnosis,
      });

      onClose();
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-zinc-900 border border-zinc-800 rounded-2xl w-full max-w-2xl shadow-2xl overflow-hidden my-8">
        <div className="px-6 py-4 border-b border-zinc-800 flex items-center justify-between bg-zinc-950/60">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-amber-500/20 border border-amber-500/30 flex items-center justify-center">
              <Clapperboard className="w-4 h-4 text-amber-400" />
            </div>
            <div>
              <h2 className="text-base font-bold text-zinc-100">Criar Novo Episódio</h2>
              <p className="text-xs text-zinc-400">
                Vincule ao programa e temporada; gere o Diagnóstico Editorial validado.
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-zinc-400 hover:text-zinc-200 p-1.5 rounded-lg hover:bg-zinc-800 cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-4 max-h-[80vh] overflow-y-auto">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400 mb-1.5">
                Programa *
              </label>
              <select
                value={showId}
                onChange={(e) => handleShowChange(e.target.value)}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 focus:outline-none focus:border-amber-500"
              >
                {shows.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.title}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400 mb-1.5">
                Temporada / Produção
              </label>
              <select
                value={productionId}
                onChange={(e) => setProductionId(e.target.value)}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 focus:outline-none focus:border-amber-500"
              >
                <option value="">Temporada Padrão do Programa</option>
                {productions
                  .filter((p) => p.showId === showId)
                  .map((p) => (
                    <option key={p.id} value={p.id}>
                      T{p.seasonNumber} — {p.title}
                    </option>
                  ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400 mb-1.5">
                Formato
              </label>
              <select
                value={format}
                onChange={(e) => setFormat(e.target.value as ShowFormat)}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 focus:outline-none focus:border-amber-500"
              >
                {FORMATS.map((f) => (
                  <option key={f} value={f}>
                    {f}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400 mb-1.5">
                Duração Alvo (min)
              </label>
              <input
                type="number"
                min={5}
                max={300}
                value={targetDurationMin}
                onChange={(e) => setTargetDurationMin(Number(e.target.value))}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div className="sm:col-span-2">
              <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400 mb-1.5">
                Título ou Tema do Episódio *
              </label>
              <input
                type="text"
                required
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Ex: A Decisão de R$ 200 Milhões: Como a AgroTech sobreviveu à seca"
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400 mb-1.5">
                Convidado Cadastrado (Opcional)
              </label>
              <select
                value={guestId}
                onChange={(e) => handleGuestSelect(e.target.value)}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 focus:outline-none focus:border-amber-500"
              >
                <option value="">Selecionar do banco ou digitar ao lado...</option>
                {guests.map((g) => (
                  <option key={g.id} value={g.id}>
                    {g.name} ({g.company})
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400 mb-1.5">
                Nome do Convidado / Participante
              </label>
              <input
                type="text"
                value={guestName}
                onChange={(e) => setGuestName(e.target.value)}
                placeholder="Ex: Dra. Helena Albuquerque"
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div className="sm:col-span-2">
              <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400 mb-1.5">
                Apresentador(a)
              </label>
              <input
                type="text"
                value={host}
                onChange={(e) => setHost(e.target.value)}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div className="sm:col-span-2">
              <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400 mb-1.5">
                Ideia Central / Contexto da Pauta *
              </label>
              <textarea
                rows={3}
                required
                value={idea}
                onChange={(e) => setIdea(e.target.value)}
                placeholder="Descreva sobre o que é o episódio, qual a história principal ou por que esse convidado é especial..."
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400 mb-1.5">
                Objetivo do Episódio
              </label>
              <input
                type="text"
                value={objective}
                onChange={(e) => setObjective(e.target.value)}
                placeholder="O que o público deve sentir ou aprender?"
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400 mb-1.5">
                Informações Adicionais / Restrições
              </label>
              <input
                type="text"
                value={additionalInfo}
                onChange={(e) => setAdditionalInfo(e.target.value)}
                placeholder="Temas sensíveis, objetos de cena..."
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 focus:outline-none focus:border-amber-500"
              />
            </div>
          </div>

          <div className="p-3.5 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <Sparkles className="w-4 h-4 text-amber-400 shrink-0" />
              <div>
                <p className="text-xs font-semibold text-amber-300">
                  Gerar Diagnóstico Editorial com IA (Schema Validado)
                </p>
                <p className="text-[11px] text-zinc-400">
                  Identifica conflito principal, transformação, momentos de impacto e pontos de pesquisa.
                </p>
              </div>
            </div>
            <input
              type="checkbox"
              checked={autoGenerateDiagnosis}
              onChange={(e) => setAutoGenerateDiagnosis(e.target.checked)}
              className="w-4 h-4 accent-amber-500 cursor-pointer"
            />
          </div>

          <div className="flex justify-end gap-3 pt-3 border-t border-zinc-800">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-sm font-medium cursor-pointer"
            >
              Cancelar
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="px-5 py-2 rounded-xl bg-amber-500 hover:bg-amber-400 disabled:opacity-50 text-zinc-950 font-semibold text-sm flex items-center gap-2 cursor-pointer"
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Gerando Diagnóstico & Persistindo...</span>
                </>
              ) : (
                <span>Criar Episódio</span>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
